services:
  database:
    image: 'postgres:latest'
    ports:
      - '5433:5432'
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_DB=postgres'
      - 'POSTGRES_PASSWORD=backend_developer@9990'
    volumes:
      - './volumes/codeminion/postgres:/var/lib/postgresql/data'
